@startjson doip_diagnostic_nack

{
    "Messageheader" : {
        "ProtocolVersion" : "uint8",
        "~ProtocolVersion" : "uint8",
        "PayloadType" : "uint16",
        "PayloadLength" : "uint32"
    },
    "SourceAddress" : "uint16",
    "TargetAddress" : "uint16", 
    "NAckCode" : "uint8",
    "UserData" : "TBD"
}

@endjson
